[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
fractionax = "Aqvk9Br2PPoTzGZbnYVxnwgpGTzPZTdcowpN9gdkRXGP"

[programs.localnet]
fractionax = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
